{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 102745,
          "sha512": "245eaf5e5e6fee0f00d2da247d2fe0cb719c875953496b3a7b641d60af0cd399208685ea3344a66582c5fd169de23d3da69e7b028390167ba97a0be46c1c0e5c",
          "sha256": "5095d45777a241e110b20d62733a014820cf468a7712e31340a132f83583577b",
          "sha1": "8742f8dcf38a9622844b3ec50f685b89d4c07ded",
          "md5": "43f1bad39fb421b1fed7b593ce7fe51c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 102745,
          "sha512": "245eaf5e5e6fee0f00d2da247d2fe0cb719c875953496b3a7b641d60af0cd399208685ea3344a66582c5fd169de23d3da69e7b028390167ba97a0be46c1c0e5c",
          "sha256": "5095d45777a241e110b20d62733a014820cf468a7712e31340a132f83583577b",
          "sha1": "8742f8dcf38a9622844b3ec50f685b89d4c07ded",
          "md5": "43f1bad39fb421b1fed7b593ce7fe51c"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_profile-1.0-sources.jar",
          "url": "video_player_android_profile-1.0-sources.jar",
          "size": 26931,
          "sha512": "ad5734295e3d2a430d515204017864b81e6c2bd974569e4ce2a12c85b290989af16e745c8b1dda6562dc7cd0cd44a39e34b5b3b36c9b0422a9568fad6332998e",
          "sha256": "e5ca87c8679e3f950902fa2d978806ff357ee80ffcd04416fc7c5a2a21000970",
          "sha1": "ff1a68e54d388b29380c02c515cb3c5779b1c02b",
          "md5": "4fab281c6eccd49db09d5aa9b4d36f4c"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_profile-1.0-javadoc.jar",
          "url": "video_player_android_profile-1.0-javadoc.jar",
          "size": 468851,
          "sha512": "f69de26a0c306bdebfacac88194f655617fc6afdbcf85be1544ba3afaa0976fcebf00f808267ff0c7a7f3105b6aa00ce7490aaf5eb68876d55f9e5a8e335e558",
          "sha256": "1991b8da182da8a4dde2e8481c96565c002d4100a93c99f3d1c34b74a3ed7b56",
          "sha1": "d9bbe004e4ca6f49a7a19e7ae0c1c895db705dc5",
          "md5": "658c184d0120b6b33cd4da7a42a56fd1"
        }
      ]
    }
  ]
}
