{
  "formatVersion": "1.1",
  "component": {
    "group": "io.livekit.plugin",
    "module": "livekit_client_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "livekit_client_release-1.0.aar",
          "url": "livekit_client_release-1.0.aar",
          "size": 31717,
          "sha512": "e18b01f3fb408aa36e47595739b2200b3149a187e1771d8e8a749141f05869eae3d63247437d316bc756e47b445073bda25991fcef37ed9153f63bb2fe44974a",
          "sha256": "ea7ad443b9e167a97786fba978b27410dc814a5dd7891ddae749cec8720c5b21",
          "sha1": "ecd6806114f88d5474a498b4354e0538452bf9b0",
          "md5": "08bae699a4981ab3d4245de79e743942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "137.7151.04"
          }
        },
        {
          "group": "io.livekit",
          "module": "noise",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "livekit_client_release-1.0.aar",
          "url": "livekit_client_release-1.0.aar",
          "size": 31717,
          "sha512": "e18b01f3fb408aa36e47595739b2200b3149a187e1771d8e8a749141f05869eae3d63247437d316bc756e47b445073bda25991fcef37ed9153f63bb2fe44974a",
          "sha256": "ea7ad443b9e167a97786fba978b27410dc814a5dd7891ddae749cec8720c5b21",
          "sha1": "ecd6806114f88d5474a498b4354e0538452bf9b0",
          "md5": "08bae699a4981ab3d4245de79e743942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit_client_release-1.0-sources.jar",
          "url": "livekit_client_release-1.0-sources.jar",
          "size": 13650,
          "sha512": "834ea86ccd8ebf8677ab288f60c62ac91101789aaca39f413a7730014a374019723cd5354a33c0d58c8e292010896ffe8a5fe488b0a065faf76ad563d3937e04",
          "sha256": "9d4e50f8e3f04f2e899326d632833f0ba7280514d8a42d718cd242d5f9749615",
          "sha1": "c6eafc94365ff80531f5cb4fa4192f776a4047eb",
          "md5": "caa139335980a13b18373a310493114b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit_client_release-1.0-javadoc.jar",
          "url": "livekit_client_release-1.0-javadoc.jar",
          "size": 316086,
          "sha512": "7f5c9fb5b8f08379595442559efb13bab9bce048f70bc78e8fce41aff9c497ac3b92fa2f59fae55fdf9ffc693f7de2de4ed13cadc734b97c419943676f0c922e",
          "sha256": "71ede72558448c8922ed5ba0fb0ce5a72b86e8ee67f9d3fe3758b45bdc7ffcc2",
          "sha1": "866d9b276734d98ecc4ecde86307a518cbd1d868",
          "md5": "9a71ced243f4fa30eaf68ffdf6d3b377"
        }
      ]
    }
  ]
}
