{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.craftsoft.keep_screen_on",
    "module": "keep_screen_on_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "keep_screen_on_debug-1.0.aar",
          "url": "keep_screen_on_debug-1.0.aar",
          "size": 4805,
          "sha512": "85260559a4ba5d1e9e5f68807877a420511664d9a8d9f9a7af4d0f94f3ac3803832731cff603205e90d6d65b44830596494eaaba3b0fc57c5beaff9271d17eb5",
          "sha256": "8c045a6d8d1770748bf9998d13b7f9a84c40a014fc508a69828f0ee217152394",
          "sha1": "0cfe19fe2566f83f0eead163fd20215f9987b356",
          "md5": "5fe7033a4441bd435a273c382ba8423a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "keep_screen_on_debug-1.0.aar",
          "url": "keep_screen_on_debug-1.0.aar",
          "size": 4805,
          "sha512": "85260559a4ba5d1e9e5f68807877a420511664d9a8d9f9a7af4d0f94f3ac3803832731cff603205e90d6d65b44830596494eaaba3b0fc57c5beaff9271d17eb5",
          "sha256": "8c045a6d8d1770748bf9998d13b7f9a84c40a014fc508a69828f0ee217152394",
          "sha1": "0cfe19fe2566f83f0eead163fd20215f9987b356",
          "md5": "5fe7033a4441bd435a273c382ba8423a"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keep_screen_on_debug-1.0-sources.jar",
          "url": "keep_screen_on_debug-1.0-sources.jar",
          "size": 1867,
          "sha512": "0897281de166783f30fcfc76d4cdf93e1e7d764279d407642d535eef2338c7f8369553fd7fc34723b7cd1318c55e9bced777779f3ac4092ca843df57cbfac313",
          "sha256": "bbc3af03a86f4e48f5669772d9af5905c2b9a82878fff31ec59218dbcf22fda6",
          "sha1": "5103a67f533df9577f9ef4e41f08a882a584cd2d",
          "md5": "34fe851b6e42864218970150e908addf"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "keep_screen_on_debug-1.0-javadoc.jar",
          "url": "keep_screen_on_debug-1.0-javadoc.jar",
          "size": 267472,
          "sha512": "069ba3ff322ba0132fde936f936f5640cd098b7ae7285e2440bc48e178ab9c8183fc587f6da4fe8991af41a44740a0bd303da8dd7854a92e92e9857640d98ede",
          "sha256": "bc368b7367d938f29bd5cd00c63d00191d3d6e9b8b94758be4465cc6b8a40d2d",
          "sha1": "fc9b7d040af715626c0931ed3a73d381fcf17537",
          "md5": "c6c06a2f5a413f834594af7fa01683b0"
        }
      ]
    }
  ]
}
