{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0.aar",
          "url": "flutter_webrtc_debug-1.0.aar",
          "size": 232204,
          "sha512": "b2e51cd7c0c049201c1847fd3687a47255a9d49ce270524e2c687084e254baddceee6ce572e6ba5a8d191a7b0bd92b9d6e959837e2e0eed80fcb1d09350c54bd",
          "sha256": "7fccee7ca364ac34f5e6cfc3cf3a656ed8d3a5d288908beef750e9eed39dbc24",
          "sha1": "4108de17bcf971d825c2cc48265d5722e467b784",
          "md5": "b702caa3a22eba8ed545ebd0c9c608ec"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "137.7151.04"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0.aar",
          "url": "flutter_webrtc_debug-1.0.aar",
          "size": 232204,
          "sha512": "b2e51cd7c0c049201c1847fd3687a47255a9d49ce270524e2c687084e254baddceee6ce572e6ba5a8d191a7b0bd92b9d6e959837e2e0eed80fcb1d09350c54bd",
          "sha256": "7fccee7ca364ac34f5e6cfc3cf3a656ed8d3a5d288908beef750e9eed39dbc24",
          "sha1": "4108de17bcf971d825c2cc48265d5722e467b784",
          "md5": "b702caa3a22eba8ed545ebd0c9c608ec"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0-sources.jar",
          "url": "flutter_webrtc_debug-1.0-sources.jar",
          "size": 103800,
          "sha512": "98f796111732d55ca6510e904d1e9463d42cdee92de373c32523f45644fa1f7348f9427a7a7371ddbe042d9074115fdd41f2e42ad436dc266a0c85f7df849443",
          "sha256": "bbb32dcafac6ada22a91ebe0c5ce9570d72b9f80cba795c52725d787df141ebd",
          "sha1": "e3be2319a98f171625986776a6175967f4638cf9",
          "md5": "134a3f6bb1bee54960667acad421d70e"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0-javadoc.jar",
          "url": "flutter_webrtc_debug-1.0-javadoc.jar",
          "size": 509609,
          "sha512": "32e06c0185e5c0ab98e9ae9eb6ce50f6af44452abfc3a264af833d0be74597d7d225f3675d826481d2b5d63a9aedf9f4c474cbef3a99ed7a7fb45af833102e4a",
          "sha256": "76483903c4d89477cfd5006ac8a24dfd2fe61b9e3c899947bd7d23e163a73162",
          "sha1": "32087da4aabc290098514760f331e4e7d439fac7",
          "md5": "3d721953de341013d7d306758d373a92"
        }
      ]
    }
  ]
}
