{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.0.aar",
          "url": "fluttertoast_debug-1.0.aar",
          "size": 8880,
          "sha512": "f23a6c3fe22d0d2d417c45c39eeb3d2c4b488bc266e6a9e840f31fb1ac817b75b91ceb7043d47aa8b03bde2d36bbe0bf6106cbeebfde01f807bfefcd5d6bbc3d",
          "sha256": "9feb382fec1d44ea25c3faed9add8ba28e37f087e3dd95d560f856fed4817b50",
          "sha1": "9678c803dbd3381f3da38faef041f029563ee1e2",
          "md5": "4660344b78633ca64ca336e1fd95e8ae"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-1.0.aar",
          "url": "fluttertoast_debug-1.0.aar",
          "size": 8880,
          "sha512": "f23a6c3fe22d0d2d417c45c39eeb3d2c4b488bc266e6a9e840f31fb1ac817b75b91ceb7043d47aa8b03bde2d36bbe0bf6106cbeebfde01f807bfefcd5d6bbc3d",
          "sha256": "9feb382fec1d44ea25c3faed9add8ba28e37f087e3dd95d560f856fed4817b50",
          "sha1": "9678c803dbd3381f3da38faef041f029563ee1e2",
          "md5": "4660344b78633ca64ca336e1fd95e8ae"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_debug-1.0-sources.jar",
          "url": "fluttertoast_debug-1.0-sources.jar",
          "size": 3120,
          "sha512": "d9ebc2d9ee6ac43fe9b5cdc36686129ada7224df1bcc4f2f8f28ae624e9a6e94c44a493482daa6e1bf349432624693b6db5a3005ec9eec1715bbe170f4c4d7b6",
          "sha256": "69e1c82573001740c8ccb654af91736acda45261c9d0bcd2bd2ac8b6b62cdb24",
          "sha1": "9522dbaa5a7420975e525cac223d4b1717db7708",
          "md5": "7898eaf3504977619edc6f80d87654f9"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_debug-1.0-javadoc.jar",
          "url": "fluttertoast_debug-1.0-javadoc.jar",
          "size": 262528,
          "sha512": "7a2b2def5355a1c72a9a8e3d6b1c3b64182a81a2b0cd96e819edf1ae494c2c50d3abc43ce37a90ddc1e3a1521c882bcd7046717416fc77a7113a9f207f8ce531",
          "sha256": "0680133fd4906eddffe56b1b81b0fbf197e9c8501ebfe79a3aeddc41acd2ed6b",
          "sha1": "380c0826a516cc597d492240df688cf208e0db58",
          "md5": "5a6cdda8f2cf3f09c00cede5893c63e7"
        }
      ]
    }
  ]
}
