{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 8152,
          "sha512": "b09db8b1215eccd7dfb434098ca1af41bd34bc13df0cf2970f05596d678eb4b0d2fb59ac9c49dacd70f39aa536db4ba6e34b43e5c403ea0f0b2083d9c6f7e7f4",
          "sha256": "498d8a06f28cd710a0f199d2ae1fe29629c015996aba59921381142a98b65e61",
          "sha1": "32293a7b974544a08a89f1ab47a6e5031b18dd63",
          "md5": "064c5d19738490dcaaa2f5b38812f23a"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 8152,
          "sha512": "b09db8b1215eccd7dfb434098ca1af41bd34bc13df0cf2970f05596d678eb4b0d2fb59ac9c49dacd70f39aa536db4ba6e34b43e5c403ea0f0b2083d9c6f7e7f4",
          "sha256": "498d8a06f28cd710a0f199d2ae1fe29629c015996aba59921381142a98b65e61",
          "sha1": "32293a7b974544a08a89f1ab47a6e5031b18dd63",
          "md5": "064c5d19738490dcaaa2f5b38812f23a"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connectivity_plus_profile-1.0-sources.jar",
          "url": "connectivity_plus_profile-1.0-sources.jar",
          "size": 5583,
          "sha512": "ea7c1fb2692a22a70bd3199f4d2dcfe0d452458aa41b333f5749eb8c96284527c85da8146ed21fc565480af5b6dba728c4c6da19a6f31ff54942f0a14fc0d4ce",
          "sha256": "50142b07be114a09ae3abf065ed608d043f1d3c50f0a015155b12015aa62b0ea",
          "sha1": "dccfbbd3a6b4442e31b677bc44e3b37cd7ded7c7",
          "md5": "b1f4c0c52c00f4f5922d3c216318e866"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connectivity_plus_profile-1.0-javadoc.jar",
          "url": "connectivity_plus_profile-1.0-javadoc.jar",
          "size": 278349,
          "sha512": "31c0f423ce12394f66312619bf8b4b91eeb234a54ec0f8987b73db75a175a68f7d5f897f17a5fbbfb6a028b87724ef17ce4fe9de2847317b569302f64da49300",
          "sha256": "5a998ecaee95a6aafe4ea93ab62af4e2b0510258a69da9b3680910855a13e8ed",
          "sha1": "ea8ca489b9d4c3e8a2da6c596bf8f071e9c0938a",
          "md5": "999edbcbf7ecc310724a141e49a753ca"
        }
      ]
    }
  ]
}
