{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.image_gallery_saver_plus",
    "module": "image_gallery_saver_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_plus_release-1.0.aar",
          "url": "image_gallery_saver_plus_release-1.0.aar",
          "size": 8667,
          "sha512": "d5ae24e3cef68dc4894a206a75e1785af2b8ed59301ac12b76e4277adbb11fc75e3ba95dff9b4bb9d69f53db8a6d0160d655a7e340b843cf04d15cd4b36c251a",
          "sha256": "d65a93ed8a5cbf4e9f57549106bd2743639b80ece8888e1032714ac3578af57a",
          "sha1": "aa5d210ad6aae1fa7836becddb45f0893ba9fa67",
          "md5": "85b97b2a25fa0532e784ed9588f9aea8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_plus_release-1.0.aar",
          "url": "image_gallery_saver_plus_release-1.0.aar",
          "size": 8667,
          "sha512": "d5ae24e3cef68dc4894a206a75e1785af2b8ed59301ac12b76e4277adbb11fc75e3ba95dff9b4bb9d69f53db8a6d0160d655a7e340b843cf04d15cd4b36c251a",
          "sha256": "d65a93ed8a5cbf4e9f57549106bd2743639b80ece8888e1032714ac3578af57a",
          "sha1": "aa5d210ad6aae1fa7836becddb45f0893ba9fa67",
          "md5": "85b97b2a25fa0532e784ed9588f9aea8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_gallery_saver_plus_release-1.0-sources.jar",
          "url": "image_gallery_saver_plus_release-1.0-sources.jar",
          "size": 3082,
          "sha512": "b389e077c18d496f0d4039d7965dfa0a892132646296b8a5b91c17db059fb33379cb04a7130c6f10f768180531f379a25618323e797040de5fb6fe48994b8568",
          "sha256": "917419896abdd03044f888406c40e0b6ee532fb68d0ed71907f8fb4ae2395928",
          "sha1": "b2a3b7a1d44ae17cf0bfcaf7f482d3bcdaae4ee4",
          "md5": "37a1a7ca60bb6ec54d6fe5b01e2f8452"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_gallery_saver_plus_release-1.0-javadoc.jar",
          "url": "image_gallery_saver_plus_release-1.0-javadoc.jar",
          "size": 271611,
          "sha512": "418a6cb923ae16caa3f69d7881f2bcf119dd712ef195e3f6eba18e4b927adbb17ba637c8e0cbf622a2b989b489d69359a5620e9fb1031ac4ee782ba4c72bad5a",
          "sha256": "538ff089c7d1f0feb29bdb173ea1a9b232ff9db2caae7b1fd7cfca550d510ad6",
          "sha1": "b9cd8740f77147c767fac028245be1bbe24ba73b",
          "md5": "d1d03c3a4c2592b8bd3d431075905f04"
        }
      ]
    }
  ]
}
