{
  "formatVersion": "1.1",
  "component": {
    "group": "io.livekit.plugin",
    "module": "livekit_client_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "livekit_client_release-1.0.aar",
          "url": "livekit_client_release-1.0.aar",
          "size": 31640,
          "sha512": "fec1c6141fd02b6ca178fca712613016c1a30af7f562b7e6c27b83c8d3f5a32b2e66ee89cd19cfd93226212facca73c2565a0a93bed16acbb69b4413043584b1",
          "sha256": "f0aff54f52affc2959031b0afdc2a5a60b9bd3fb5514a7c96e887354c752799a",
          "sha1": "bacd63b67259016237e06349321278c8fce27149",
          "md5": "63df3f96199d60b2f87eff4a8b264dbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "137.7151.04"
          }
        },
        {
          "group": "io.livekit",
          "module": "noise",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "livekit_client_release-1.0.aar",
          "url": "livekit_client_release-1.0.aar",
          "size": 31640,
          "sha512": "fec1c6141fd02b6ca178fca712613016c1a30af7f562b7e6c27b83c8d3f5a32b2e66ee89cd19cfd93226212facca73c2565a0a93bed16acbb69b4413043584b1",
          "sha256": "f0aff54f52affc2959031b0afdc2a5a60b9bd3fb5514a7c96e887354c752799a",
          "sha1": "bacd63b67259016237e06349321278c8fce27149",
          "md5": "63df3f96199d60b2f87eff4a8b264dbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit_client_release-1.0-sources.jar",
          "url": "livekit_client_release-1.0-sources.jar",
          "size": 13632,
          "sha512": "a9e1d0f53f2a934f91ec24abec2cb7e50af87da131d1bf576173cae9687e5c575f2b0045abb4cd3b01f57f48afb89f07d3edcdf1b306d75c95dcffb71fcf7925",
          "sha256": "a26bd00fe823d6501e7de8bfb3cf41c33678920ebd855d782bdb32768656552c",
          "sha1": "8a85be1f10c4bb8e4cb10f14aa0a930cbfd0e8d4",
          "md5": "2335e4db6d45ae81fdf8d99147b16135"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit_client_release-1.0-javadoc.jar",
          "url": "livekit_client_release-1.0-javadoc.jar",
          "size": 316086,
          "sha512": "7f5c9fb5b8f08379595442559efb13bab9bce048f70bc78e8fce41aff9c497ac3b92fa2f59fae55fdf9ffc693f7de2de4ed13cadc734b97c419943676f0c922e",
          "sha256": "71ede72558448c8922ed5ba0fb0ce5a72b86e8ee67f9d3fe3758b45bdc7ffcc2",
          "sha1": "866d9b276734d98ecc4ecde86307a518cbd1d868",
          "md5": "9a71ced243f4fa30eaf68ffdf6d3b377"
        }
      ]
    }
  ]
}
