{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-1.0.aar",
          "url": "sqflite_android_release-1.0.aar",
          "size": 43037,
          "sha512": "c1e960da1af39d2c001b55b698c7b7ce3b5bd4c6e8f03b69102056aed13ecac250a97c1abfd0b69cf1b1742f56227a98426b9fd1dae17ed89130b95ca94f8449",
          "sha256": "4796e19b1f068db0547ddc47f83ed52dc9156e76f90efca4420209c83560e903",
          "sha1": "2f6ce102aa92242495b68d12c5f42f0816a02c5d",
          "md5": "b21daafb9f18fbc2f2417fbbbb780990"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-1.0.aar",
          "url": "sqflite_android_release-1.0.aar",
          "size": 43037,
          "sha512": "c1e960da1af39d2c001b55b698c7b7ce3b5bd4c6e8f03b69102056aed13ecac250a97c1abfd0b69cf1b1742f56227a98426b9fd1dae17ed89130b95ca94f8449",
          "sha256": "4796e19b1f068db0547ddc47f83ed52dc9156e76f90efca4420209c83560e903",
          "sha1": "2f6ce102aa92242495b68d12c5f42f0816a02c5d",
          "md5": "b21daafb9f18fbc2f2417fbbbb780990"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-1.0-sources.jar",
          "url": "sqflite_android_release-1.0-sources.jar",
          "size": 23663,
          "sha512": "8fab4715d7e3d96747ef1de92c03dff003c7f72e23c9a2bada2ac1a0daad359c22677107af7f95eed76447893685131f72c8c4575f646eb6db0cd0d6960f5c63",
          "sha256": "a51229e1462df34685f523fbb152893e17abfe4811849e1295d6c0bf25477e3e",
          "sha1": "a594f17941e467782009913a999b4812257c41f5",
          "md5": "5f4db26adb3c92e861735d64021ac12f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-1.0-javadoc.jar",
          "url": "sqflite_android_release-1.0-javadoc.jar",
          "size": 339847,
          "sha512": "a3487817a545779a4cae0594e5c87b477a42e8f7d48ecc014f45ea7c1ecfd23671d67f5db051ea176b41637dab1b4d10ccbfe497732db2617eb895339f809c60",
          "sha256": "ec0fbadc7ed06698ef85fbc624eec9f01d801775036e80ca8b21a48208fd343a",
          "sha1": "c813866e483dfc6854f7a8784e005919a45b5d90",
          "md5": "179993301ce10c53a4398189940fb85b"
        }
      ]
    }
  ]
}
