{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.0.aar",
          "url": "fluttertoast_profile-1.0.aar",
          "size": 8885,
          "sha512": "3910040f6309d24f9cecea1e6ed7c96ede0cbc543746ff58aaaa87257af6485c45208cecea9d525e04aec26e647f5fcc3a1b5eb68d11f1302478016ae2468e60",
          "sha256": "e73a8adb246005cbe0a1c9ee1bd82fc030afb4678b0bc33128c65ee68cb59657",
          "sha1": "2ce158546fcbe3cd60a05dfe29505525dd66ab5e",
          "md5": "878b9c4d1e9a06bfc030e45008292402"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_profile-1.0.aar",
          "url": "fluttertoast_profile-1.0.aar",
          "size": 8885,
          "sha512": "3910040f6309d24f9cecea1e6ed7c96ede0cbc543746ff58aaaa87257af6485c45208cecea9d525e04aec26e647f5fcc3a1b5eb68d11f1302478016ae2468e60",
          "sha256": "e73a8adb246005cbe0a1c9ee1bd82fc030afb4678b0bc33128c65ee68cb59657",
          "sha1": "2ce158546fcbe3cd60a05dfe29505525dd66ab5e",
          "md5": "878b9c4d1e9a06bfc030e45008292402"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_profile-1.0-sources.jar",
          "url": "fluttertoast_profile-1.0-sources.jar",
          "size": 3120,
          "sha512": "d9ebc2d9ee6ac43fe9b5cdc36686129ada7224df1bcc4f2f8f28ae624e9a6e94c44a493482daa6e1bf349432624693b6db5a3005ec9eec1715bbe170f4c4d7b6",
          "sha256": "69e1c82573001740c8ccb654af91736acda45261c9d0bcd2bd2ac8b6b62cdb24",
          "sha1": "9522dbaa5a7420975e525cac223d4b1717db7708",
          "md5": "7898eaf3504977619edc6f80d87654f9"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_profile-1.0-javadoc.jar",
          "url": "fluttertoast_profile-1.0-javadoc.jar",
          "size": 262528,
          "sha512": "7a2b2def5355a1c72a9a8e3d6b1c3b64182a81a2b0cd96e819edf1ae494c2c50d3abc43ce37a90ddc1e3a1521c882bcd7046717416fc77a7113a9f207f8ce531",
          "sha256": "0680133fd4906eddffe56b1b81b0fbf197e9c8501ebfe79a3aeddc41acd2ed6b",
          "sha1": "380c0826a516cc597d492240df688cf208e0db58",
          "md5": "5a6cdda8f2cf3f09c00cede5893c63e7"
        }
      ]
    }
  ]
}
