{
  "formatVersion": "1.1",
  "component": {
    "group": "io.livekit.plugin",
    "module": "livekit_client_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "livekit_client_debug-1.0.aar",
          "url": "livekit_client_debug-1.0.aar",
          "size": 32755,
          "sha512": "5acc9d2869d4cabcacf785f3a705c17684b2094a76a3cf87a68f12613fbb541cc9c9fa276a52ba1ca7220dd659f054fb1a7b5930f10c3db86a2b3d4c9d4c3d7c",
          "sha256": "587d34d4534009c8abc7e763123c7973f50744e1305c4e869cda620550b575f9",
          "sha1": "f2254c5304b97daeba7096dba9ff218b027b0f20",
          "md5": "2bfdff253f92b4273c6668c0481c6d2d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "137.7151.04"
          }
        },
        {
          "group": "io.livekit",
          "module": "noise",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "livekit_client_debug-1.0.aar",
          "url": "livekit_client_debug-1.0.aar",
          "size": 32755,
          "sha512": "5acc9d2869d4cabcacf785f3a705c17684b2094a76a3cf87a68f12613fbb541cc9c9fa276a52ba1ca7220dd659f054fb1a7b5930f10c3db86a2b3d4c9d4c3d7c",
          "sha256": "587d34d4534009c8abc7e763123c7973f50744e1305c4e869cda620550b575f9",
          "sha1": "f2254c5304b97daeba7096dba9ff218b027b0f20",
          "md5": "2bfdff253f92b4273c6668c0481c6d2d"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit_client_debug-1.0-sources.jar",
          "url": "livekit_client_debug-1.0-sources.jar",
          "size": 13632,
          "sha512": "a9e1d0f53f2a934f91ec24abec2cb7e50af87da131d1bf576173cae9687e5c575f2b0045abb4cd3b01f57f48afb89f07d3edcdf1b306d75c95dcffb71fcf7925",
          "sha256": "a26bd00fe823d6501e7de8bfb3cf41c33678920ebd855d782bdb32768656552c",
          "sha1": "8a85be1f10c4bb8e4cb10f14aa0a930cbfd0e8d4",
          "md5": "2335e4db6d45ae81fdf8d99147b16135"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "livekit_client_debug-1.0-javadoc.jar",
          "url": "livekit_client_debug-1.0-javadoc.jar",
          "size": 316086,
          "sha512": "7f5c9fb5b8f08379595442559efb13bab9bce048f70bc78e8fce41aff9c497ac3b92fa2f59fae55fdf9ffc693f7de2de4ed13cadc734b97c419943676f0c922e",
          "sha256": "71ede72558448c8922ed5ba0fb0ce5a72b86e8ee67f9d3fe3758b45bdc7ffcc2",
          "sha1": "866d9b276734d98ecc4ecde86307a518cbd1d868",
          "md5": "9a71ced243f4fa30eaf68ffdf6d3b377"
        }
      ]
    }
  ]
}
