{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-1.0.aar",
          "url": "flutter_webrtc_release-1.0.aar",
          "size": 219762,
          "sha512": "dbbea5ffb694cb17a6ac7289b413ef69ce1d5285b11edecc07a19dd12d4f3f67b9dfc6333d6ce64c25a9de7fbc7fd7d2097f0a97b327eff7983d15c2eeb4da30",
          "sha256": "1014122f8df32a86910b60a85d934f8289babb27a4d393f832f8bd2355eea90f",
          "sha1": "234de9ceb7ebc6869ba63e3af4780340de109c98",
          "md5": "aa4e13e56418997a3895ee8530d4881f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "137.7151.04"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-1.0.aar",
          "url": "flutter_webrtc_release-1.0.aar",
          "size": 219762,
          "sha512": "dbbea5ffb694cb17a6ac7289b413ef69ce1d5285b11edecc07a19dd12d4f3f67b9dfc6333d6ce64c25a9de7fbc7fd7d2097f0a97b327eff7983d15c2eeb4da30",
          "sha256": "1014122f8df32a86910b60a85d934f8289babb27a4d393f832f8bd2355eea90f",
          "sha1": "234de9ceb7ebc6869ba63e3af4780340de109c98",
          "md5": "aa4e13e56418997a3895ee8530d4881f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-1.0-sources.jar",
          "url": "flutter_webrtc_release-1.0-sources.jar",
          "size": 103400,
          "sha512": "212e6eac79f53d0868d088790bdaba0d25ec428d349e14105a0248e046a2c71f70d90318d2e019bc061337f2435a5e4e3141f7f74fce6194eb6bd5d0b83bdb1d",
          "sha256": "428580f4cdacb4d98bd2322132c3b4be62b8872fedde6bc9e938f825647e6de8",
          "sha1": "3ccc3761f6a0f613f4b9f2dd0f8ee3c374243ce5",
          "md5": "889372b8f7a3fe4cbf4c58b7160350bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-1.0-javadoc.jar",
          "url": "flutter_webrtc_release-1.0-javadoc.jar",
          "size": 509609,
          "sha512": "32e06c0185e5c0ab98e9ae9eb6ce50f6af44452abfc3a264af833d0be74597d7d225f3675d826481d2b5d63a9aedf9f4c474cbef3a99ed7a7fb45af833102e4a",
          "sha256": "76483903c4d89477cfd5006ac8a24dfd2fe61b9e3c899947bd7d23e163a73162",
          "sha1": "32087da4aabc290098514760f331e4e7d439fac7",
          "md5": "3d721953de341013d7d306758d373a92"
        }
      ]
    }
  ]
}
