{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-1.0.aar",
          "url": "flutter_webrtc_release-1.0.aar",
          "size": 219759,
          "sha512": "dfe3315c5c44d07bcc3ac2655c4d0f334c9e5e1b8bd01c9d65297893c81d9116c6daad38a42dc415fa8755947af65bf2ff62739440b1f9c78790036aa51b564d",
          "sha256": "ced8605897e3d2b0c010b220fa6e6d1cd4ddd6db7a5251109d704d861d15f867",
          "sha1": "f11df99aaba1e6febfbcbc72ef8b8deca5a0fbb1",
          "md5": "7d63126ef37532ff695dc96ed0bbc54d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "137.7151.04"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-1.0.aar",
          "url": "flutter_webrtc_release-1.0.aar",
          "size": 219759,
          "sha512": "dfe3315c5c44d07bcc3ac2655c4d0f334c9e5e1b8bd01c9d65297893c81d9116c6daad38a42dc415fa8755947af65bf2ff62739440b1f9c78790036aa51b564d",
          "sha256": "ced8605897e3d2b0c010b220fa6e6d1cd4ddd6db7a5251109d704d861d15f867",
          "sha1": "f11df99aaba1e6febfbcbc72ef8b8deca5a0fbb1",
          "md5": "7d63126ef37532ff695dc96ed0bbc54d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-1.0-sources.jar",
          "url": "flutter_webrtc_release-1.0-sources.jar",
          "size": 104447,
          "sha512": "d04d72dd5a8d5d1aea2ea88779cd8cc9eaf7fa5acf6a1ad2c8111ae4add0f50a579bf57a30dec2b3fefbe6bd7a6686010243838156a735eda9916cd3222599d0",
          "sha256": "ae0def8f644eb7c02b2e664ce61f4ac45e917f066f343e296d432571884e01c2",
          "sha1": "b2e1379cca18da616223e7d144ff2bd52181bce5",
          "md5": "2316b920fd0a5907592385782efa7ce7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-1.0-javadoc.jar",
          "url": "flutter_webrtc_release-1.0-javadoc.jar",
          "size": 509609,
          "sha512": "32e06c0185e5c0ab98e9ae9eb6ce50f6af44452abfc3a264af833d0be74597d7d225f3675d826481d2b5d63a9aedf9f4c474cbef3a99ed7a7fb45af833102e4a",
          "sha256": "76483903c4d89477cfd5006ac8a24dfd2fe61b9e3c899947bd7d23e163a73162",
          "sha1": "32087da4aabc290098514760f331e4e7d439fac7",
          "md5": "3d721953de341013d7d306758d373a92"
        }
      ]
    }
  ]
}
