{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 102619,
          "sha512": "2f30084b731dbcbd5377c09ffd2cf02691d675a7ec308f0160b1e7d464f082f74d64a1b2f02a0d4566a01b6778a0107cac8e7eb91b79ab5bf357fdc23aeabc0d",
          "sha256": "08e0ff05b561a13af0efc36247cf20bce4697b7241b1037857267f1f9c9ad29d",
          "sha1": "58fd4d464e1234eb2d1e536571033fe93641601b",
          "md5": "5409bb190246de00e2cad96425802d1f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 102619,
          "sha512": "2f30084b731dbcbd5377c09ffd2cf02691d675a7ec308f0160b1e7d464f082f74d64a1b2f02a0d4566a01b6778a0107cac8e7eb91b79ab5bf357fdc23aeabc0d",
          "sha256": "08e0ff05b561a13af0efc36247cf20bce4697b7241b1037857267f1f9c9ad29d",
          "sha1": "58fd4d464e1234eb2d1e536571033fe93641601b",
          "md5": "5409bb190246de00e2cad96425802d1f"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_debug-1.0-sources.jar",
          "url": "video_player_android_debug-1.0-sources.jar",
          "size": 26931,
          "sha512": "ad5734295e3d2a430d515204017864b81e6c2bd974569e4ce2a12c85b290989af16e745c8b1dda6562dc7cd0cd44a39e34b5b3b36c9b0422a9568fad6332998e",
          "sha256": "e5ca87c8679e3f950902fa2d978806ff357ee80ffcd04416fc7c5a2a21000970",
          "sha1": "ff1a68e54d388b29380c02c515cb3c5779b1c02b",
          "md5": "4fab281c6eccd49db09d5aa9b4d36f4c"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_debug-1.0-javadoc.jar",
          "url": "video_player_android_debug-1.0-javadoc.jar",
          "size": 468851,
          "sha512": "f69de26a0c306bdebfacac88194f655617fc6afdbcf85be1544ba3afaa0976fcebf00f808267ff0c7a7f3105b6aa00ce7490aaf5eb68876d55f9e5a8e335e558",
          "sha256": "1991b8da182da8a4dde2e8481c96565c002d4100a93c99f3d1c34b74a3ed7b56",
          "sha1": "d9bbe004e4ca6f49a7a19e7ae0c1c895db705dc5",
          "md5": "658c184d0120b6b33cd4da7a42a56fd1"
        }
      ]
    }
  ]
}
