{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.aar",
          "url": "flutter_inappwebview_android_profile-1.0.aar",
          "size": 542619,
          "sha512": "d1ef07282e6a3844f065c454e43eb3a9565a5d7eb727a836bc95e60c7984c8df2b644ca2d71b8dd552b4ebf75d5d7f7de60a2baebe9293a612ab73c9bef39a9e",
          "sha256": "dd10c8ab7637ae0aa8c8f81cc9126482e8912ffe9f886138e77c60981e329150",
          "sha1": "ad9d2d437624fbb5242fc876eb29444d1a8cbd72",
          "md5": "8f0566183d7a184c5f5e6e11c40dd498"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.aar",
          "url": "flutter_inappwebview_android_profile-1.0.aar",
          "size": 542619,
          "sha512": "d1ef07282e6a3844f065c454e43eb3a9565a5d7eb727a836bc95e60c7984c8df2b644ca2d71b8dd552b4ebf75d5d7f7de60a2baebe9293a612ab73c9bef39a9e",
          "sha256": "dd10c8ab7637ae0aa8c8f81cc9126482e8912ffe9f886138e77c60981e329150",
          "sha1": "ad9d2d437624fbb5242fc876eb29444d1a8cbd72",
          "md5": "8f0566183d7a184c5f5e6e11c40dd498"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0-sources.jar",
          "url": "flutter_inappwebview_android_profile-1.0-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0-javadoc.jar",
          "url": "flutter_inappwebview_android_profile-1.0-javadoc.jar",
          "size": 1167598,
          "sha512": "030fffa163697837fb6e841076b64b625b3f3b7117c601da91c621daba8ad18003b0c57759f48062b7ae9affc98a66a9e7e397c26cb7efbf37d1bd9806ceaee1",
          "sha256": "58b1fc085a12b1bcbcde1e88dc51b50057f4c61695d9512bf57f5d545c8fc2bf",
          "sha1": "c9d9a1c81302a4cb33806cd30a2a154a62322cc2",
          "md5": "25ab59547a810d32a6ae265a531d3ae7"
        }
      ]
    }
  ]
}
