{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.aar",
          "url": "flutter_inappwebview_android_release-1.0.aar",
          "size": 455146,
          "sha512": "a99a52d9bdc08f55260bf5945cb6b42f8faf90c0326f42eca1aa55a1483e6c8f2207c9ffdf9c3942387a6ad691575f080dafaef8bd5bc68cd29dd527a01bcf63",
          "sha256": "834a264b83278a64f7d59d4269350bff5e9c9f0fe446d8cfedd0de9d6245c09e",
          "sha1": "7171a1429734cb6825d28121ecbd6fa601dfa46b",
          "md5": "b4482388ed87de9926817ee351a721c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b5990e5ccc5e325fd24f0746e7d6689bbebc7c65"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.aar",
          "url": "flutter_inappwebview_android_release-1.0.aar",
          "size": 455146,
          "sha512": "a99a52d9bdc08f55260bf5945cb6b42f8faf90c0326f42eca1aa55a1483e6c8f2207c9ffdf9c3942387a6ad691575f080dafaef8bd5bc68cd29dd527a01bcf63",
          "sha256": "834a264b83278a64f7d59d4269350bff5e9c9f0fe446d8cfedd0de9d6245c09e",
          "sha1": "7171a1429734cb6825d28121ecbd6fa601dfa46b",
          "md5": "b4482388ed87de9926817ee351a721c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0-sources.jar",
          "url": "flutter_inappwebview_android_release-1.0-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0-javadoc.jar",
          "url": "flutter_inappwebview_android_release-1.0-javadoc.jar",
          "size": 1167503,
          "sha512": "e82151dca8f0d592f2e9d3f6c420af68cf1bb0c19e2d49a5f193a2d3bb98ef4f78b25c7e302e586f238cb6c69104413f803a03d50e0596cade4a8b6c0de4ebb9",
          "sha256": "3b28d2451dec6fd11c3183bf629a38c0efc9487f4a80cca923ef2b9fe1282f36",
          "sha1": "35946168bdb5338f44810be9db1e3431da1eb468",
          "md5": "05d7cbde163038abcda795000343ff78"
        }
      ]
    }
  ]
}
